version: '3.9'
services:
    # demo
    demo42:
        container_name: demo42
        build:
            context: .
            dockerfile: Dockerfile
        image: demo42:1.0
        volumes:
          - .:/home/app
          - /home/app/node_modules
        working_dir: /home/app
        command: npm run dev